### PR TITLE
Automatically update collection by parsing Achievements.log

### PR DESCRIPTION
**Pull request by riQQ**

### CODE REVIEW

**Comment by riQQ** [comment]
@ko-vasilev do you intend to pull this some time?

**Comment by ko-vasilev** [comment]
@riQQ I'll review it later. Thanks for contribution.

**Comment by riQQ** [comment]
This still works for arena rewards and end of season rewards, but sadly not for pack opening at the moment.

**Comment by culinko** [comment]
Afaik pack openings are gone from Achievements.log and arena rewards are gone from Rachelle.log in 4.1. Are you 100% sure they are still present?

**Comment by riQQ** [comment]
If I'm not mistaken, end of season rewards worked at the end of last season. I'll check tomorrow.

**Comment by riQQ** [comment]
End of season rewards aren't logged at the moment. I'll check Arena rewards, too.

**Comment by culinko** [comment]
I remembered that we talked about it on IRC so I checked my logs to get an approximate guess. Arena rewards were removed in Patch 3.0.0.9786, end of season rewards were removed in Patch 3.1.0.10357 or Patch 3.2.0.10604.

**Comment by riQQ** [comment]
Thanks for the information.

**Pull request closed without merging**
