### PR TITLE
Add MSoG + Un'Goro cards.

### PR DESCRIPTION
**Pull request by adriencarbonne**

### CODE REVIEW

**Comment by Chow89** [comment]
Can you built a release of your PR in your forked repo, so everyone interested can use it until @ko-vasilev merge this?

**Comment by adriencarbonne** [comment]
Here you are: https://github.com/adriencarbonne/Hearthstone-Collection-Tracker/releases

Adding Mean Streets of Gadgetzan compatibility also fixes the fatal error when using the latest version of Hearthstone-Tracker!

**Comment by adriencarbonne** [comment]
Plugin DLL with Un'Goro cards available at: https://github.com/adriencarbonne/Hearthstone-Collection-Tracker/releases

**Comment by Chow89** [comment]
The project is now maintained by HearthSim. https://github.com/HearthSim/Hearthstone-Collection-Tracker

**Pull request closed without merging**
